### ISSUE TITLE
Does this work for Nvidia Jetson, such as Nvidia Nano, Xavier, and AGX Xavier?

### ISSUE THREAD

**Issue by ArtofWar-dev** [koendv/xtensa-esp32-elf-raspberrypi#2]
Currently working developing on these board would love to have some support since they are all ARM64 like Raspberry PI.

**Comment by koendv** [comment]
Nvidia boards run Ubuntu. Building the esp32 toolchain on Nvidia ought to work.
Download the build script for the esp32 toolchain from https://github.com/koendv/xtensa-esp32-elf-raspberrypi/blob/master/build.sh
Execute the lines one by one. There might be some differences in the names of the packages you need to install with apt-get. But you ought to end up with a working toolchain.
