### ISSUE TITLE
Are there any instructions on how to fully integrate this with Arduino 1.8.12 on a 64 bit Raspberry Pi

### ISSUE THREAD

**Issue by MarkDH102** [koendv/xtensa-esp32-elf-raspberrypi#3]
OK. I've installed the aforementioned .deb file.
However, I have no idea how to use the files.
I've disappeared down the usual Linux/Google rabbit hole trying to find out what to do next.
I've added the json file for the esp32 to the boards manager,but when I select the esp32 to install, I get an error regarding mkspiffs not being suitable for my system.
I have this all working on a Windows system and know how to configure the board manager in the arduino IDE. But I want to try and make a 64bit pi4 my daily driver.
How have you managed to get esp32 arduino IDE working on a 64 bit pi install using these files?
Cheers for any guidance.

**Comment by koendv** [comment]
Added a section on how to install [arduino for esp32 on raspberry pi os 64-bit](https://github.com/koendv/xtensa-esp32-elf-raspberrypi#arduino-esp32-on-raspberry-pi-64-bit).

**Comment by MarkDH102** [comment]
Many, many thanks for this. It's all working - well, it's compiled/linked a basic example for me. Haven't tried downloading to the device yet.
Also, I had to change the address entered into the board manager to :
https://raw.githubusercontent.com/koendv/xtensa-esp32-elf-raspberrypi/master/package_esp32_dev_index.json
The reason being, the URL you gave was putting a HTML file (with the correct name) onto my system, but it had HTML content, not the JSON content that was expected...

**Comment by koendv** [comment]
OK. Updated .json url. Added compilation instructions for mkspiffs.
