### ISSUE TITLE
Unclear build instructions

### ISSUE THREAD

**Issue by AkbarRamzan** [koendv/xtensa-esp32-elf-raspberrypi#4]
The instructions in the readme states you should run `sudo apt install ./xtensa-esp32-elf_8.2.0-2020r2_arm64.deb` but it doesn't tell you how to properly build the deb file in order to run it.
The shell script `build.sh` actually ends up creating a folder in your home directory. Either at ~/src/esp or ~/esp rather than the directory `build.sh` is located in.
The build instructions should be updated to have clearer instructions as to what the user needs to do as simply running the build and package script wont work. I had to modify the script.

**Comment by koendv** [comment]
On Sun, 14 Mar 2021 01:59:51 -0800
AkbarRamzan ***@***.***> wrote:

> The instructions in the readme states you should run `sudo apt
> install ./xtensa-esp32-elf_8.2.0-2020r2_arm64.deb` but it doesn't
> tell you how to properly build the deb file in order to run it. The
> shell script `build.sh` actually ends up creating a folder in your
> home directory. Either at ~/src/esp or ~/esp rather than the
> directory `build.sh` is located in.
> 

OK. What would you suggest?

koen
